### PR TITLE
Create compiled-with-dmd.yml

### PR DESCRIPTION
**Pull request by re-fox**
Simple rule, addresses https://github.com/fireeye/capa-rules/issues/259

### CODE REVIEW

**Comment by re-fox** [comment]
Linter is failing on sample, testable sample is here -> https://github.com/fireeye/capa-testfiles/pull/70

**Review by williballenthin — APPROVED** [review]
looks great

**Comment by williballenthin** [comment]
discussion on the proposed test file, then we can merge this.

**Comment by re-fox** [comment]
hash has been updated to reflect https://github.com/fireeye/capa-testfiles/pull/72

**Pull request merged**
