### PR TITLE
Fix #117 - Add encrypt-data-using-sosemanuk

### LINKED ISSUE #117: encrypt-data-using-sosemanuk
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

encrypt-data-using-sosemanuk

## Examples

From https://labs.sentinelone.com/enter-the-maze-demystifying-an-affiliate-involved-in-maze-snow/ :

image

## Features

Cryptographic constants

## Additional context

PR incoming

### Namespace

data-manipulation/encryption/sosemanuk

### References

https://labs.sentinelone.com/enter-the-maze-demystifying-an-affiliate-involved-in-maze-snow/

### Other rule meta information

N/A

### PR DESCRIPTION
**Pull request by recvfrom**
Fixes #117

### CODE REVIEW

**Comment by williballenthin** [comment]
awesome!

one request:
  - would you please add the referenced example into the [capa-testfiles](https://github.com/fireeye/capa-testfiles/) repo?

and an idea:
  - extend the rule to also catch the `0x54655307` constant, and maybe also the `ROL 7` instruction (via `mnemonic` and `number`)

**Comment by williballenthin** [comment]
if there's a good reason not to add the other features, no worries, this is otherwise ready to go

**Comment by recvfrom** [comment]
good thinking, I'll do that now

**Review by williballenthin — APPROVED** [review]
nice!

**Comment by williballenthin** [comment]
thank you @recvfrom !

**Pull request merged**
