### PR TITLE
Create compiled-with-pyarmor.yml

### PR DESCRIPTION
**Pull request by itsreallynick**
Coverage for Dashingsoft's pyarmor, as referenced in [recent public communications](https://twitter.com/stvemillertime/status/1349032548580483073) from the Honorable Doctor Steven Miller of the FireEye Institute (@stvemillertime).
This is a basic rule to help people understand what may have obfuscated the file they are analyzing.
Fellow scientists may debate whether or not this is truly a compiler or an obfuscator belonging elsewhere in the namespace tree, but to them I say: 'ok sure I barely even know if I'm doing this right so, fine'
It may also be worth looking at https://github.com/liftoff/pyminifier 👀  and then just making a wider collection of PE obfuscator/compilers from scripting languages. I am using GitHub in dark mode if it helps.

image
Ok don't mind if I do...
https://user-images.githubusercontent.com/7584935/104348958-4f949380-54d0-11eb-8625-5b2bfed6993c.mov

### CODE REVIEW

**Comment by itsreallynick** [comment]
Yo @stvemillertime - linter wants an example. Get them some hot fire up in this yaml

**Review by williballenthin — APPROVED** [review]
send it!

**Comment by williballenthin** [comment]
```
  FAIL: filename doesn't match the rule name: Rename rule file to match the rule name, expected: "compiled-with-dashingsoft-pyarmor.yml", found: "compiled-with-pyarmor.yml"
  FAIL: missing examples: Add meta.examples so that the rule can be tested and verified
```

**Comment by itsreallynick** [comment]
>   FAIL: filename doesn't match the rule name: Rename rule file to match the rule name, expected: "compiled-with-dashingsoft-pyarmor.yml", found: "compiled-with-pyarmor.yml"
Updated.

> FAIL: missing examples: Add meta.examples so that the rule can be tested and verified
Have pinged @stvemillertime to put THE BEST sample hash in there, but I'll go find one if he doesn't add it soon. brb

**Comment by itsreallynick** [comment]
> Have pinged @stvemillertime to put THE BEST sample hash in there, but I'll go find one if he doesn't add it soon. brb

Adding these now

examples:
  - 0e054493c82baf64b30f3cb0349843dedd8f8e25e8f53eec0a9d7ed2dbadb20a.exe_
  - 000286df4376dc71b1f5d8367b2da929bc016c441651365268077a08548d0e67.exe_

**Comment by williballenthin** [comment]
test file added here: https://github.com/fireeye/capa-testfiles/commit/3f438ab56e65d1d8a6088fb99d9cf9463007bf89

**Comment by mr-tz** [comment]
thank you - thrilling video! 😄

**Pull request merged**
