### PR TITLE
add rules describing hardcoded DNS servers

### PR DESCRIPTION
**Pull request by williballenthin**
initially wanted to describe behavior of this TIGERPLUG dropper here: https://www.virustotal.com/gui/file/784ceff596d94ef365ae261ae43a83c43d52e04dc46b09a8fb5960772bca4a00/content/strings

but the DNS servers are not referenced directly by the dropper, and i haven't gotten around to extracting the payloads.

### CODE REVIEW

**Comment by re-fox** [comment]
Good idea, I was looking through my yara rules and I've also got some looking for Hurricane Electric's DNS

Hurricane Electric’s nameservers:
```
216.218.130.2
216.218.131.2
216.218.132.2 
216.66.1.2.
```

**Comment by williballenthin** [comment]
HE added

**Review by mr-tz — APPROVED** [review]
lgtm

**Review by re-fox — APPROVED** [review]

**Comment by re-fox** [comment]
Agreed, good idea!

**Pull request merged**
