### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by 0ssigeno**
Hi everyone, while working on capa I found a single key misspelled and a wrong syntax for inline comments.

### CODE REVIEW

**Comment by mr-tz** [comment]
Yes, very good. Thank you. Only real change in the MD file seems to be here: https://github.com/fireeye/capa-rules/pull/101/files#diff-dfa361526d5079822f4b78d61b1bc8d2R481. However, I think this PR applied `dos2unix`, so am good with merging as is.

**Comment by 0ssigeno** [comment]
Yeah, i'm sorry about the format.md, the ide did its thing and I didn't correctly review the change.
If is a problem let me know that i will try to revert it!

**Comment by mr-tz** [comment]
Hm, unfortunately, we're not very consistent with the line terminators. Please revert the `format.md` back and then we can merge.

**Comment by 0ssigeno** [comment]
Technically it has CRLF now (if xxd doesn't lie to me). Still don't know why it shows the entire file format.md changed.
If this is still an issue, honestly I don't know how to fix it without closing and reopening a PR

**Comment by mr-tz** [comment]
still shows up as follows for me:
```
$ file doc/format.md
doc/format.md: ASCII text, with very long lines
```

does your git apply changes automatically maybe?

**Comment by 0ssigeno** [comment]
Yep, you were right. Before each push the ide decided to remove the CRLF. Sorry for messing up the history, if you prefer to have a clean one, I can close and open another clean PR.

**Comment by mr-tz** [comment]
Yes, @Ana06 taught me to rebase and keep a clean history (see https://github.com/fireeye/capa-rules/pull/98#pullrequestreview-466883647). If you don't want to rebase a new PR works as well. Thank you very much and sorry for the back and forth.

**Comment by 0ssigeno** [comment]
Completely fine and understandable, I would have asked the same. Will open the new PR asap!

**Pull request closed without merging**
