### PR TITLE
decompress data using aPLib

### PR DESCRIPTION
**Pull request by fboldewin**
New rule which detects decompression function of library aPLib

### CODE REVIEW

**Review by mr-tz — COMMENTED** [review]
Awesome, thanks for the contribution!

Testing on `DAA13AE302FE8B618DDBF590537443EF` the rule works in IDA but not in vivisect.
I'm having a little trouble identifying the features here in the `aP_depack` source code and am curious how well this matches across other compilations.

In general, we could leverage capa to identify higher level features of the algorithm vs. the occurrence of multiple instructions (or maybe a combination).

For example:
```c
                                        if (offs >= 32000) {
						len++;
					}
					if (offs >= 1280) {
						len++;
					}
					if (offs < 128) {
						len += 2;
					}
```

Any thoughts on this?

**Comment by mr-tz** [comment]
I modified/abstracted your rule to:

```yml
rule:
  meta:
    name: decompress data using aPLib
    namespace: data-manipulation/compression
    author:
      - "@r3c0nst (Frank Boldewin)"
      - moritz.raabe@fireeye.com
    description: detects decompression function of library aPLib
    scope: function
    references:
      - https://ibsensoftware.com/files/aPLib-1.1.1.zip
    examples:
      - B43FCA5283BFC7022553EFF663683834:0x424
      - DAA13AE302FE8B618DDBF590537443EF:0x419F50
      - 6CE584F4F2157C63D5DD239A12A3DCEC:0x40AC20
  features:
    - and:
      - description: aP_depack
      - basic block:
        - and:
          - mnemonic: cmp
          - number: 32000
      - basic block:
        - and:
          - mnemonic: cmp
          - or:
            - number: 127
            - number: 128
      - count(characteristic(calls from)): 2 or more  # calls aP_getbit and aP_getgamma
      - match: contain loop
```

# Tests

```
$ capa -t aPLib tests/data/daa13ae302fe8b618ddbf590537443ef.exe_ -vv
...

decompress data using aPLib
namespace    data-manipulation/compression
author       @r3c0nst (Frank Boldewin), moritz.raabe@fireeye.com
description  detects decompression function of library aPLib
scope        function
references   https://ibsensoftware.com/files/aPLib-1.1.1.zip
examples     B43FCA5283BFC7022553EFF663683834:0x424, DAA13AE302FE8B618DDBF590537443EF:0x419F50, 6CE584F4F2157C63D5DD239A12A3DCEC:0x40AC20
function @ 0x419CA0
  and: = aP_depack
    subscope:
      and:
        mnemonic: cmp @ 0x419FB1
        number: 0x7D00 @ 0x419FB1
    subscope:
      and:
        mnemonic: cmp @ 0x419FBD
        or:
          number: 0x7F @ 0x419FBD
    count(characteristic(calls from)): 2 or more @ 0x419FD3, 0x419FDD, 0x419FDF
    match: contain loop @ 0x419CA0
      or:
        characteristic: loop @ 0x419CA0
        characteristic: tight loop @ 0x419F7F
```

```
$ capa -t aPLib tests/data/b43fca5283bfc7022553eff663683834 -vv --format sc32
...

decompress data using aPLib
namespace    data-manipulation/compression
author       @r3c0nst (Frank Boldewin), moritz.raabe@fireeye.com
description  detects decompression function of library aPLib
scope        function
references   https://ibsensoftware.com/files/aPLib-1.1.1.zip
examples     B43FCA5283BFC7022553EFF663683834:0x424, DAA13AE302FE8B618DDBF590537443EF:0x419F50, 6CE584F4F2157C63D5DD239A12A3DCEC:0x40AC20
function @ 0x690424
  and: = aP_depack
    subscope:
      and: = offs >= 32000
        mnemonic: cmp @ 0x690485
        number: 0x7D00 @ 0x690485
    subscope:
      and: = offs < 128
        mnemonic: cmp @ 0x690491
        or:
          number: 0x7F @ 0x690491
    count(characteristic(calls from)): 2 or more @ 0x6904A7, 0x6904B1, 0x6904B3
    match: contain loop @ 0x690424
      or:
        characteristic: loop @ 0x690424
        characteristic: tight loop @ 0x690453
```

```
$ capa -t aPLib tests/data/6ce584f4f2157c63d5dd239a12a3dcec -vv
...

decompress data using aPLib
namespace    data-manipulation/compression
author       @r3c0nst (Frank Boldewin), moritz.raabe@fireeye.com
description  detects decompression function of library aPLib
scope        function
references   https://ibsensoftware.com/files/aPLib-1.1.1.zip
examples     B43FCA5283BFC7022553EFF663683834:0x424, DAA13AE302FE8B618DDBF590537443EF:0x419F50, 6CE584F4F2157C63D5DD239A12A3DCEC:0x40AC20
function @ 0x40AC20
  and: = aP_depack
    subscope:
      and: = offs >= 32000
        mnemonic: cmp @ 0x40AC81
        number: 0x7D00 @ 0x40AC81
    subscope:
      and: = offs < 128
        mnemonic: cmp @ 0x40AC8D
        or:
          number: 0x7F @ 0x40AC8D
    count(characteristic(calls from)): 2 or more @ 0x40ACA3, 0x40ACAD, 0x40ACAF
    match: contain loop @ 0x40AC20
      or:
        characteristic: loop @ 0x40AC20
        characteristic: tight loop @ 0x40AC4F
```

These match now, but I wonder if there's many FPs and this needs to be tightened up.

**Comment by re-fox** [comment]
@mr-tz I'll check out your rule and run it against some test samples to get an idea of FPs (if any at all)

**Comment by mr-tz** [comment]
> 
> 
> @mr-tz I'll check out your rule and run it against some test samples to get an idea of FPs (if any at all)

great, thanks a lot!

**Comment by re-fox** [comment]
Based on some quick analysis from the `capa-testfiles` repo

|Sample|Offset|Notes|
|---|---|---|
|d7ff81ff775d4ab50d31ac1e962c8c4dea7ff9f280aa2b42ddd06760a5665002|0x402C7E|True Positive|
|971e599e6e707349eccea2fd4c8e5f67|0x427000|Potential FP, hitting on .vmp section
|daa13ae302fe8b618ddbf590537443ef | 0x419CA0| True Positive|
|3fdfb2d522e7deecaaaf2f87420f7e75|0x4115B3| True Positive|
|02179f3ba93663074740b5c0d283bae2|0x4C8850| True Positive|

**Comment by mr-tz** [comment]
For the record, the original rule also works in vivisect once we change the instruction mnemonic:
```diff
<           - mnemonic: lods
---
>           - mnemonic: lodsb

```

**Comment by mr-tz** [comment]
Thanks for the tests, @re-fox! Looks like it's working quite well.
If no one objects, I'll get the modified rule ready to merge.

**Comment by Ana06** [comment]
I am preparing capa v1.6.1 release. Please do not merge this PR until capa v1.6.1 is released to avoid that it is included in the release and not mentioned in the changelog. 🙏

**Comment by Ana06** [comment]
capa v1.6.1 is released 😉

**Comment by mr-tz** [comment]
further discussion on this in #313

**Pull request closed without merging**
