### PR TITLE
update mappings for mbc (part 3)

### PR DESCRIPTION
**Pull request by dzbeck**
Added Malware Behavior Catalog (MBC) and ATT&CK mappings in the data-manipulation namespace (plus a couple in anti-analysis and executable namespaces).

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
outstanding!

i love how MBC is growing in such a way that we can highlight the results in capa

**Comment by williballenthin** [comment]
@dzbeck have you noticed any areas of MBC that has light coverage within capa? we can prioritize the development of rules there.

**Review by mr-tz — APPROVED** [review]
Great, thank you!

**Comment by dzbeck** [comment]
@williballenthin nothing has jumped out as far as light coverage, but thinking about it now, you might want to look at some of the anti-status analysis behaviors (e.g., executable code obfuscation).

**Pull request merged**
